name: Greetings Issuer or Pull Requester <3

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello @${{ github.actor }} , thank you for submitting an issue! FYI @${{ github.repository_owner }}'
        pr-message: 'Hello @${{ github.actor }} , thank you submitting a pull request! FYI @${{ github.repository_owner }}'
